/* 兵庫県 名産品記憶ゲーム / 出題・出典データ Ver.1.4 */
(function () {
  "use strict";

  const HYOGO_MEISAN_DATA = {
    version: "1.4",
    updatedAt: "2026-09-06",
    sourcePolicy: "主産地が複数にまたがる品目は、代表地・中心地・発祥地・地区所在地として問題文を限定しています。",
    regions: [
      { id: "kobe", label: "神戸" },
      { id: "hanshin-s", label: "阪神南" },
      { id: "hanshin-n", label: "阪神北" },
      { id: "higashi", label: "東播磨" },
      { id: "kita", label: "北播磨" },
      { id: "naka", label: "中播磨" },
      { id: "nishi", label: "西播磨" },
      { id: "tajima", label: "但馬" },
      { id: "tamba", label: "丹波" },
      { id: "awaji", label: "淡路" }
    ],
    sources: [
      { id: "A", group: "県・国の基礎資料", publisher: "兵庫県", title: "兵庫県内地場産業一覧〔令和5年（2023）数値〕", url: "https://web.pref.hyogo.lg.jp/sr09/documents/jibasanngyor5.pdf" },
      { id: "B", group: "県・国の基礎資料", publisher: "兵庫県", title: "兵庫県の伝統的工芸品の紹介", url: "https://web.pref.hyogo.lg.jp/sr09/ie07_000000016.html" },
      { id: "C", group: "県・国の基礎資料", publisher: "兵庫県", title: "兵庫県の地場産業の紹介", url: "https://web.pref.hyogo.lg.jp/sr09/ie07_000000017.html" },
      { id: "D01", group: "市町・関係機関の公式情報", publisher: "小野市", title: "播州そろばん・小野金物", url: "https://www.city.ono.hyogo.jp/soshikikarasagasu/chiikishinkobu_sangyosozoka/gyomuannai/5/1/1672.html" },
      { id: "D02", group: "市町・関係機関の公式情報", publisher: "三木市", title: "三木金物", url: "https://www.city.miki.lg.jp/odekakeplus/odekake-07.html" },
      { id: "D03", group: "市町・関係機関の公式情報", publisher: "たつの市", title: "特産品", url: "https://www.city.tatsuno.lg.jp/soshiki/1023/gyomu/2/5/1678.html" },
      { id: "D04", group: "市町・関係機関の公式情報", publisher: "兵庫県", title: "有馬の人形筆", url: "https://web.pref.hyogo.lg.jp/sr09/ie07_000000026.html" },
      { id: "D05", group: "市町・関係機関の公式情報", publisher: "兵庫県", title: "有馬籠", url: "https://web.pref.hyogo.lg.jp/sr09/ie07_000000027.html" },
      { id: "D06", group: "市町・関係機関の公式情報", publisher: "神戸市", title: "ケミカルシューズ", url: "https://www.city.kobe.lg.jp/a93457/kanko/fashion/kobechemicalshoes/index.html?_gl=1*kjxmxu*_ga*MTM4MTMwMDMxNS4xNzg4NjcyMTI0*_ga_6PVWK3MVF5*czE3ODg2NzIxMjMkbzEkZzEkdDE3ODg2NzIxNDckajM2JGwwJGgw" },
      { id: "D07", group: "市町・関係機関の公式情報", publisher: "Wikipedia", title: "神戸ワイン", url: "https://ja.wikipedia.org/wiki/%E7%A5%9E%E6%88%B8%E3%83%AF%E3%82%A4%E3%83%B3" },
      { id: "D08", group: "市町・関係機関の公式情報", publisher: "伊丹市観光物産協会", title: "伊丹酒", url: "https://itami-kankou.com/itami" },
      { id: "D09", group: "市町・関係機関の公式情報", publisher: "兵庫県", title: "名塩紙", url: "https://web.pref.hyogo.lg.jp/sr09/ie07_000000035.html" },
      { id: "D10", group: "市町・関係機関の公式情報", publisher: "川西市", title: "川西いちじく", url: "https://www.city.kawanishi.hyogo.jp/shiseijoho/shokai/kankouannai/ichijiku.html" },
      { id: "D11", group: "市町・関係機関の公式情報", publisher: "兵庫県", title: "三田青磁", url: "https://web.pref.hyogo.lg.jp/sr09/jibasan/kougeihin/sandaseiji.html" },
      { id: "D12", group: "市町・関係機関の公式情報", publisher: "明石市", title: "明石のたからもの", url: "https://www.city.akashi.lg.jp/shise/koho/citysales/taneakashi-enjoy.html" },
      { id: "D13", group: "市町・関係機関の公式情報", publisher: "明石観光協会", title: "明石焼き", url: "https://www.akashi-mercato.jp/shop/category/23/?pageno=1" },
      { id: "D14", group: "市町・関係機関の公式情報", publisher: "加古川市", title: "かつめし", url: "https://www.city.kakogawa.lg.jp/material/files/group/1/shichoteireiR080521-3.pdf" },
      { id: "D15", group: "市町・関係機関の公式情報", publisher: "加東市", title: "山田錦", url: "https://www.city.kato.lg.jp/kakukanogoannai/machidukuriseisakubu/kikakuseisaku/seisakusuishin/news/news/14953.html" },
      { id: "D16", group: "市町・関係機関の公式情報", publisher: "西脇市", title: "播州織", url: "https://www.city.nishiwaki.lg.jp/kakukanogoannai/sangyoukatsuryokusaiseibu/syoukourouseika/koyosangyosinko/syoukoshinko/jibasangyou/bansyuori.html" },
      { id: "D17", group: "市町・関係機関の公式情報", publisher: "西脇市", title: "観光・特産品", url: "https://www.city.nishiwaki.lg.jp/kankotokusan/index.html" },
      { id: "D18", group: "市町・関係機関の公式情報", publisher: "多可町", title: "杉原紙", url: "https://www.town.taka.lg.jp/category_guide/detail/id%3D38848" },
      { id: "D19", group: "市町・関係機関の公式情報", publisher: "姫路市", title: "姫路の特産品", url: "https://www.city.himeji.lg.jp/kanko/0000005172.html" },
      { id: "D20", group: "市町・関係機関の公式情報", publisher: "福崎町", title: "もち麦", url: "https://www.town.fukusaki.hyogo.jp/0000001135.html" },
      { id: "D21", group: "市町・関係機関の公式情報", publisher: "神河町", title: "神河ゆず", url: "https://www.town.kamikawa.hyogo.jp/0000000510.html" },
      { id: "D22", group: "市町・関係機関の公式情報", publisher: "相生市", title: "特産品", url: "https://www.city.aioi.lg.jp/soshiki/chiikishinko/tokusanbutsu1.html" },
      { id: "D23", group: "市町・関係機関の公式情報", publisher: "赤穂市", title: "お土産・特産品", url: "https://www.city.ako.lg.jp/kensetsu/kankou/omiyage/index.html" },
      { id: "D24", group: "市町・関係機関の公式情報", publisher: "赤穂市", title: "特産品", url: "https://www.city.ako.lg.jp/tokusanhin.html" },
      { id: "D25", group: "市町・関係機関の公式情報", publisher: "太子町", title: "特産品・地場産業", url: "https://www.town.hyogo-taishi.lg.jp/soshikikarasagasu/keizai/tokusannhinjibasangyo/1426397834236.html" },
      { id: "D26", group: "市町・関係機関の公式情報", publisher: "上郡町", title: "上郡モロヘイヤ", url: "https://www.town.kamigori.hyogo.jp/soshiki/nourin/gyomuannai/nousei/1/1905.html" },
      { id: "D27", group: "市町・関係機関の公式情報", publisher: "佐用町", title: "佐用ホルモン焼きうどん", url: "https://www.town.sayo.lg.jp/cms-sypher/www/event/detail.jsp?id=8779" },
      { id: "D28", group: "市町・関係機関の公式情報", publisher: "宍粟市", title: "しそうの特産品", url: "https://www.city.shiso.lg.jp/material/files/group/41/04megurimeguru.pdf" },
      { id: "D29", group: "市町・関係機関の公式情報", publisher: "豊岡市", title: "買う・特産品", url: "https://www.city.toyooka.lg.jp/kanko/kau/index.html" },
      { id: "D30", group: "市町・関係機関の公式情報", publisher: "養父市", title: "特産品", url: "https://www.city.yabu.hyogo.jp/material/files/group/10/66767630.pdf" },
      { id: "D31", group: "市町・関係機関の公式情報", publisher: "朝来市", title: "岩津ねぎ", url: "https://www.city.asago.hyogo.jp/soshiki/23/1627.html" },
      { id: "D32", group: "市町・関係機関の公式情報", publisher: "香美町", title: "観光ガイド", url: "https://www.town.mikata-kami.lg.jp/material/files/group/4/kamicyougaido2_2025.pdf" },
      { id: "D33", group: "市町・関係機関の公式情報", publisher: "丹波市", title: "丹波布伝承館", url: "https://www.city.tamba.lg.jp/soshiki/shiminkatsudoka/gyomuannai/10/tanbanunodensyoukan/index.html" },
      { id: "D34", group: "市町・関係機関の公式情報", publisher: "丹波市農業ポータル", title: "特産品", url: "https://agri-tambacity.jp/about/about_products/" },
      { id: "D35", group: "市町・関係機関の公式情報", publisher: "兵庫県", title: "丹波黒大豆", url: "https://web.pref.hyogo.lg.jp/nk12/af11_000000115.html" },
      { id: "D36", group: "市町・関係機関の公式情報", publisher: "丹波篠山市", title: "丹波篠山黒枝豆", url: "https://www.city.tambasasayama.lg.jp/soshikikarasagasu/nomiyakoseisakuka/tokusan/edamame/29483.html" },
      { id: "D37", group: "市町・関係機関の公式情報", publisher: "JA丹波ささやま", title: "特産品", url: "https://www.ja-tanbasasayama.or.jp/" },
      { id: "D38", group: "市町・関係機関の公式情報", publisher: "JA全農兵庫", title: "淡路島たまねぎ", url: "https://www.hg.zennoh.or.jp/agriculture/yasai-hana/onion.html" },
      { id: "D39", group: "市町・関係機関の公式情報", publisher: "兵庫県", title: "淡路島の線香", url: "https://web.pref.hyogo.lg.jp/kk03/dayori2406/pickup1.html" },
      { id: "D40", group: "市町・関係機関の公式情報", publisher: "農林水産省", title: "淡路島手延べそうめん（GI）", url: "https://www.maff.go.jp/j/shokusan/gi_act/register/0176/index.html" },
      { id: "D41", group: "市町・関係機関の公式情報", publisher: "南あわじ市", title: "淡路瓦", url: "https://www.city.minamiawaji.hyogo.jp/soshiki/shoukou/awaji-kawara.html" },
      { id: "D42", group: "市町・関係機関の公式情報", publisher: "南あわじ市", title: "淡路島3年とらふぐ", url: "https://www.city.minamiawaji.hyogo.jp/soshiki/suisan/torafugu.html" },
      { id: "D43", group: "市町・関係機関の公式情報", publisher: "兵庫県公式観光サイト", title: "但馬牛", url: "https://www.hyogo-tourism.jp/experience/detail_5273.html" },
      { id: "D44", group: "市町・関係機関の公式情報", publisher: "南あわじ市", title: "淡路島サクラマス", url: "https://www.city.minamiawaji.hyogo.jp/site/awajishima-sakuramasu/" },
      { id: "D45", group: "市町・関係機関の公式情報", publisher: "丹波篠山市公式観光サイト", title: "立杭陶の郷", url: "https://tourism.sasayama.jp/suenosato/" },
      { id: "D46", group: "市町・関係機関の公式情報", publisher: "灘五郷酒造組合", title: "灘五郷", url: "https://www.nadagogo.ne.jp/" },
      { id: "D47", group: "市町・関係機関の公式情報", publisher: "兵庫県", title: "神戸家具", url: "https://web.pref.hyogo.lg.jp/sr09/jibasan/20.html" },
      { id: "D48", group: "市町・関係機関の公式情報", publisher: "兵庫県", title: "神戸アパレル", url: "https://web.pref.hyogo.lg.jp/sr09/jibasan/13.html" },
      { id: "D49", group: "市町・関係機関の公式情報", publisher: "兵庫県", title: "真珠加工", url: "https://web.pref.hyogo.lg.jp/sr09/jibasan/27.html" },
      { id: "D50", group: "市町・関係機関の公式情報", publisher: "兵庫県", title: "三田鈴鹿竹器", url: "https://web.pref.hyogo.lg.jp/sr09/ie07_000000045.html" }
    ],
    questions: [
      { id: "HMG-001", specialty: "有馬の人形筆", prompt: "有馬の人形筆の産地はどこですか？", answerId: "28109", answerLabel: "神戸市北区", answerScope: "area", regionId: "kobe", evidenceType: "産地", sourceIds: ["D04"] },
      { id: "HMG-002", specialty: "有馬籠", prompt: "有馬籠の産地はどこですか？", answerId: "28109", answerLabel: "神戸市北区", answerScope: "area", regionId: "kobe", evidenceType: "産地", sourceIds: ["D05"] },
      { id: "HMG-003", specialty: "ケミカルシューズ", prompt: "ケミカルシューズ発祥の地として知られる区はどこですか？", answerId: "28106", answerLabel: "神戸市長田区", answerScope: "area", regionId: "kobe", evidenceType: "発祥地", sourceIds: ["D06"] },
      { id: "HMG-004", specialty: "神戸ワイン", prompt: "神戸ワインの産地を、ゲームの10区域で答えてください。", answerId: "kobe", answerLabel: "神戸", answerScope: "region", regionId: "kobe", evidenceType: "産地（市域内）", sourceIds: ["D07"] },
      { id: "HMG-005", specialty: "神戸家具", prompt: "神戸家具の主産地を、ゲームの10区域で答えてください。", answerId: "kobe", answerLabel: "神戸", answerScope: "region", regionId: "kobe", evidenceType: "主産地", sourceIds: ["D47"] },
      { id: "HMG-006", specialty: "神戸アパレル", prompt: "神戸アパレルの主産地を、ゲームの10区域で答えてください。", answerId: "kobe", answerLabel: "神戸", answerScope: "region", regionId: "kobe", evidenceType: "主産地", sourceIds: ["D48"] },
      { id: "HMG-007", specialty: "真珠加工", prompt: "真珠加工の主産地を、ゲームの10区域で答えてください。", answerId: "kobe", answerLabel: "神戸", answerScope: "region", regionId: "kobe", evidenceType: "主産地", sourceIds: ["D49"] },
      { id: "HMG-008", specialty: "伊丹酒", prompt: "清酒「伊丹酒」発祥の地として知られる市はどこですか？", answerId: "28207", answerLabel: "伊丹市", answerScope: "area", regionId: "hanshin-n", evidenceType: "発祥地", sourceIds: ["D08"] },
      { id: "HMG-009", specialty: "名塩紙", prompt: "名塩紙の産地はどこですか？", answerId: "28204", answerLabel: "西宮市", answerScope: "area", regionId: "hanshin-s", evidenceType: "産地", sourceIds: ["D09"] },
      { id: "HMG-010", specialty: "川西いちじく", prompt: "川西いちじくの産地はどこですか？", answerId: "28217", answerLabel: "川西市", answerScope: "area", regionId: "hanshin-n", evidenceType: "特産", sourceIds: ["D10"] },
      { id: "HMG-011", specialty: "三田青磁", prompt: "三田青磁の産地はどこですか？", answerId: "28219", answerLabel: "三田市", answerScope: "area", regionId: "hanshin-n", evidenceType: "産地", sourceIds: ["D11"] },
      { id: "HMG-012", specialty: "三田鈴鹿竹器", prompt: "三田鈴鹿竹器の産地はどこですか？", answerId: "28219", answerLabel: "三田市", answerScope: "area", regionId: "hanshin-n", evidenceType: "産地", sourceIds: ["D50"] },
      { id: "HMG-013", specialty: "明石だこ", prompt: "明石だこの産地はどこですか？", answerId: "28203", answerLabel: "明石市", answerScope: "area", regionId: "higashi", evidenceType: "特産", sourceIds: ["D12"] },
      { id: "HMG-014", specialty: "明石焼き", prompt: "明石焼きの名物のまちはどこですか？", answerId: "28203", answerLabel: "明石市", answerScope: "area", regionId: "higashi", evidenceType: "名物", sourceIds: ["D13"] },
      { id: "HMG-015", specialty: "かつめし", prompt: "かつめしのご当地グルメのまちはどこですか？", answerId: "28210", answerLabel: "加古川市", answerScope: "area", regionId: "higashi", evidenceType: "名物", sourceIds: ["D14"] },
      { id: "HMG-016", specialty: "宝殿石（竜山石）", prompt: "宝殿石（竜山石）の産地はどこですか？", answerId: "28216", answerLabel: "高砂市", answerScope: "area", regionId: "higashi", evidenceType: "主産地", sourceIds: ["A"] },
      { id: "HMG-017", specialty: "山田錦", prompt: "山田錦の特A地区を持つ市はどこですか？", answerId: "28228", answerLabel: "加東市", answerScope: "area", regionId: "kita", evidenceType: "産地", sourceIds: ["D15"] },
      { id: "HMG-018", specialty: "播州織", prompt: "播州織の中心地として知られる市はどこですか？", answerId: "28213", answerLabel: "西脇市", answerScope: "area", regionId: "kita", evidenceType: "中心地", sourceIds: ["D16"] },
      { id: "HMG-019", specialty: "播州釣針", prompt: "播州釣針の一大産地である市はどこですか？", answerId: "28213", answerLabel: "西脇市", answerScope: "area", regionId: "kita", evidenceType: "代表産地", sourceIds: ["D17"] },
      { id: "HMG-020", specialty: "杉原紙", prompt: "杉原紙の産地はどこですか？", answerId: "28365", answerLabel: "多可町", answerScope: "area", regionId: "kita", evidenceType: "産地", sourceIds: ["D18"] },
      { id: "HMG-021", specialty: "播州そろばん", prompt: "播州そろばんの産地はどこですか？", answerId: "28218", answerLabel: "小野市", answerScope: "area", regionId: "kita", evidenceType: "主産地", sourceIds: ["A", "D01"] },
      { id: "HMG-022", specialty: "小野金物（家庭刃物）", prompt: "小野金物として知られる家庭刃物の代表地はどこですか？", answerId: "28218", answerLabel: "小野市", answerScope: "area", regionId: "kita", evidenceType: "代表地", sourceIds: ["A", "D01"] },
      { id: "HMG-023", specialty: "播州鎌", prompt: "播州鎌の産地はどこですか？", answerId: "28218", answerLabel: "小野市", answerScope: "area", regionId: "kita", evidenceType: "産地", sourceIds: ["B", "D01"] },
      { id: "HMG-024", specialty: "三木金物", prompt: "三木金物の代表産地はどこですか？", answerId: "28215", answerLabel: "三木市", answerScope: "area", regionId: "kita", evidenceType: "代表地", sourceIds: ["A", "D02"] },
      { id: "HMG-025", specialty: "ゴルフ用具", prompt: "ゴルフ用具の主産地を、ゲームの10区域で答えてください。", answerId: "naka", answerLabel: "中播磨", answerScope: "region", regionId: "naka", evidenceType: "主産地", sourceIds: ["A"] },
      { id: "HMG-026", specialty: "姫路の菓子", prompt: "姫路の菓子の主産地はどこですか？", answerId: "28201", answerLabel: "姫路市", answerScope: "area", regionId: "naka", evidenceType: "主産地", sourceIds: ["A"] },
      { id: "HMG-027", specialty: "姫革細工", prompt: "姫革細工の産地はどこですか？", answerId: "28201", answerLabel: "姫路市", answerScope: "area", regionId: "naka", evidenceType: "産地", sourceIds: ["B", "D19"] },
      { id: "HMG-028", specialty: "明珍火箸", prompt: "明珍火箸の産地はどこですか？", answerId: "28201", answerLabel: "姫路市", answerScope: "area", regionId: "naka", evidenceType: "産地", sourceIds: ["B", "D19"] },
      { id: "HMG-029", specialty: "姫路おでん", prompt: "姫路おでんの名物のまちはどこですか？", answerId: "28201", answerLabel: "姫路市", answerScope: "area", regionId: "naka", evidenceType: "名物", sourceIds: ["D19"] },
      { id: "HMG-030", specialty: "鎖", prompt: "鎖の主産地はどこですか？", answerId: "28201", answerLabel: "姫路市", answerScope: "area", regionId: "naka", evidenceType: "主産地", sourceIds: ["A"] },
      { id: "HMG-031", specialty: "にかわ・ゼラチン", prompt: "にかわ・ゼラチンの主産地はどこですか？", answerId: "28201", answerLabel: "姫路市", answerScope: "area", regionId: "naka", evidenceType: "主産地", sourceIds: ["A"] },
      { id: "HMG-032", specialty: "福崎もち麦", prompt: "福崎もち麦の産地はどこですか？", answerId: "28443", answerLabel: "福崎町", answerScope: "area", regionId: "naka", evidenceType: "特産", sourceIds: ["D20"] },
      { id: "HMG-033", specialty: "神河ゆず", prompt: "神河ゆずの産地はどこですか？", answerId: "28446", answerLabel: "神河町", answerScope: "area", regionId: "naka", evidenceType: "特産", sourceIds: ["D21"] },
      { id: "HMG-034", specialty: "揖保乃糸", prompt: "揖保乃糸の代表地として最も適切な市はどこですか？", answerId: "28229", answerLabel: "たつの市", answerScope: "area", regionId: "nishi", evidenceType: "代表地", sourceIds: ["A", "D03"] },
      { id: "HMG-035", specialty: "龍野醤油", prompt: "龍野醤油の産地はどこですか？", answerId: "28229", answerLabel: "たつの市", answerScope: "area", regionId: "nishi", evidenceType: "主産地", sourceIds: ["A", "D03"] },
      { id: "HMG-036", specialty: "室津かき", prompt: "室津かきの産地はどこですか？", answerId: "28229", answerLabel: "たつの市", answerScope: "area", regionId: "nishi", evidenceType: "特産", sourceIds: ["D03"] },
      { id: "HMG-037", specialty: "相生かき", prompt: "相生かきの産地はどこですか？", answerId: "28208", answerLabel: "相生市", answerScope: "area", regionId: "nishi", evidenceType: "特産", sourceIds: ["D22"] },
      { id: "HMG-038", specialty: "赤穂の塩", prompt: "赤穂の塩の産地はどこですか？", answerId: "28212", answerLabel: "赤穂市", answerScope: "area", regionId: "nishi", evidenceType: "特産", sourceIds: ["D23"] },
      { id: "HMG-039", specialty: "赤穂緞通", prompt: "赤穂緞通の産地はどこですか？", answerId: "28212", answerLabel: "赤穂市", answerScope: "area", regionId: "nishi", evidenceType: "産地", sourceIds: ["B", "D24"] },
      { id: "HMG-040", specialty: "赤穂雲火焼", prompt: "赤穂雲火焼の産地はどこですか？", answerId: "28212", answerLabel: "赤穂市", answerScope: "area", regionId: "nishi", evidenceType: "産地", sourceIds: ["B", "D24"] },
      { id: "HMG-041", specialty: "太子いちじく", prompt: "太子いちじくの産地はどこですか？", answerId: "28464", answerLabel: "太子町", answerScope: "area", regionId: "nishi", evidenceType: "特産", sourceIds: ["D25"] },
      { id: "HMG-042", specialty: "上郡モロヘイヤ", prompt: "上郡モロヘイヤの産地はどこですか？", answerId: "28481", answerLabel: "上郡町", answerScope: "area", regionId: "nishi", evidenceType: "特産", sourceIds: ["D26"] },
      { id: "HMG-043", specialty: "佐用ホルモン焼きうどん", prompt: "佐用ホルモン焼きうどんの名物のまちはどこですか？", answerId: "28501", answerLabel: "佐用町", answerScope: "area", regionId: "nishi", evidenceType: "名物", sourceIds: ["D27"] },
      { id: "HMG-044", specialty: "宍粟自然薯", prompt: "宍粟自然薯の産地はどこですか？", answerId: "28227", answerLabel: "宍粟市", answerScope: "area", regionId: "nishi", evidenceType: "特産", sourceIds: ["D28"] },
      { id: "HMG-045", specialty: "播州山崎藍染織", prompt: "播州山崎藍染織の山崎地区がある市はどこですか？", answerId: "28227", answerLabel: "宍粟市", answerScope: "area", regionId: "nishi", evidenceType: "地区所在地", sourceIds: ["B"] },
      { id: "HMG-046", specialty: "豊岡鞄", prompt: "豊岡鞄の産地はどこですか？", answerId: "28209", answerLabel: "豊岡市", answerScope: "area", regionId: "tajima", evidenceType: "主産地", sourceIds: ["A", "D29"] },
      { id: "HMG-047", specialty: "豊岡杞柳細工", prompt: "豊岡杞柳細工の産地はどこですか？", answerId: "28209", answerLabel: "豊岡市", answerScope: "area", regionId: "tajima", evidenceType: "産地", sourceIds: ["B", "D29"] },
      { id: "HMG-048", specialty: "出石焼", prompt: "出石焼の産地はどこですか？", answerId: "28209", answerLabel: "豊岡市", answerScope: "area", regionId: "tajima", evidenceType: "主産地", sourceIds: ["A", "D29"] },
      { id: "HMG-049", specialty: "城崎麦わら細工", prompt: "城崎麦わら細工の産地はどこですか？", answerId: "28209", answerLabel: "豊岡市", answerScope: "area", regionId: "tajima", evidenceType: "産地", sourceIds: ["B", "D29"] },
      { id: "HMG-050", specialty: "出石そば", prompt: "出石そばの名物のまちはどこですか？", answerId: "28209", answerLabel: "豊岡市", answerScope: "area", regionId: "tajima", evidenceType: "名物", sourceIds: ["D29"] },
      { id: "HMG-051", specialty: "津居山かに", prompt: "津居山かにの産地はどこですか？", answerId: "28209", answerLabel: "豊岡市", answerScope: "area", regionId: "tajima", evidenceType: "特産", sourceIds: ["D29"] },
      { id: "HMG-052", specialty: "朝倉山椒", prompt: "朝倉山椒の産地はどこですか？", answerId: "28222", answerLabel: "養父市", answerScope: "area", regionId: "tajima", evidenceType: "特産", sourceIds: ["D30"] },
      { id: "HMG-053", specialty: "八鹿豚", prompt: "八鹿豚の産地はどこですか？", answerId: "28222", answerLabel: "養父市", answerScope: "area", regionId: "tajima", evidenceType: "特産", sourceIds: ["D30"] },
      { id: "HMG-054", specialty: "岩津ねぎ", prompt: "岩津ねぎの産地はどこですか？", answerId: "28225", answerLabel: "朝来市", answerScope: "area", regionId: "tajima", evidenceType: "特産", sourceIds: ["D31"] },
      { id: "HMG-055", specialty: "香住ガニ", prompt: "香住ガニの産地はどこですか？", answerId: "28585", answerLabel: "香美町", answerScope: "area", regionId: "tajima", evidenceType: "特産", sourceIds: ["D32"] },
      { id: "HMG-056", specialty: "但馬牛", prompt: "但馬牛の代表産地を、ゲームの10区域で答えてください。", answerId: "tajima", answerLabel: "但馬", answerScope: "region", regionId: "tajima", evidenceType: "代表地域", sourceIds: ["D43"] },
      { id: "HMG-057", specialty: "丹波布", prompt: "丹波布の産地はどこですか？", answerId: "28223", answerLabel: "丹波市", answerScope: "area", regionId: "tamba", evidenceType: "産地", sourceIds: ["B", "D33"] },
      { id: "HMG-058", specialty: "丹波大納言小豆", prompt: "丹波大納言小豆の代表産地として知られる市はどこですか？", answerId: "28223", answerLabel: "丹波市", answerScope: "area", regionId: "tamba", evidenceType: "代表地", sourceIds: ["D34"] },
      { id: "HMG-059", specialty: "丹波栗", prompt: "丹波栗の代表産地として知られる市はどこですか？", answerId: "28223", answerLabel: "丹波市", answerScope: "area", regionId: "tamba", evidenceType: "代表地", sourceIds: ["D34"] },
      { id: "HMG-060", specialty: "丹波黒大豆", prompt: "丹波黒大豆の主産地を、ゲームの10区域で答えてください。", answerId: "tamba", answerLabel: "丹波", answerScope: "region", regionId: "tamba", evidenceType: "主産地", sourceIds: ["D35"] },
      { id: "HMG-061", specialty: "丹波篠山黒枝豆", prompt: "丹波篠山黒枝豆の産地はどこですか？", answerId: "28221", answerLabel: "丹波篠山市", answerScope: "area", regionId: "tamba", evidenceType: "特産", sourceIds: ["D36"] },
      { id: "HMG-062", specialty: "丹波篠山山の芋", prompt: "丹波篠山山の芋の産地はどこですか？", answerId: "28221", answerLabel: "丹波篠山市", answerScope: "area", regionId: "tamba", evidenceType: "特産", sourceIds: ["D37"] },
      { id: "HMG-063", specialty: "丹波立杭焼", prompt: "丹波立杭焼の立杭地区がある市はどこですか？", answerId: "28221", answerLabel: "丹波篠山市", answerScope: "area", regionId: "tamba", evidenceType: "地区所在地", sourceIds: ["A", "B", "D45"] },
      { id: "HMG-064", specialty: "淡路島たまねぎ", prompt: "淡路島たまねぎの産地を、ゲームの10区域で答えてください。", answerId: "awaji", answerLabel: "淡路", answerScope: "region", regionId: "awaji", evidenceType: "島内全域の産地", sourceIds: ["D38"] },
      { id: "HMG-065", specialty: "淡路島の線香", prompt: "淡路島の線香が始まった江井地区がある市はどこですか？", answerId: "28226", answerLabel: "淡路市", answerScope: "area", regionId: "awaji", evidenceType: "発祥地", sourceIds: ["A", "D39"] },
      { id: "HMG-066", specialty: "淡路島手延べそうめん", prompt: "淡路島手延べそうめんの産地はどこですか？", answerId: "28224", answerLabel: "南あわじ市", answerScope: "area", regionId: "awaji", evidenceType: "産地", sourceIds: ["A", "D40"] },
      { id: "HMG-067", specialty: "淡路瓦", prompt: "淡路瓦の産地はどこですか？", answerId: "28224", answerLabel: "南あわじ市", answerScope: "area", regionId: "awaji", evidenceType: "主産地", sourceIds: ["A", "D41"] },
      { id: "HMG-068", specialty: "淡路島3年とらふぐ", prompt: "淡路島3年とらふぐの産地はどこですか？", answerId: "28224", answerLabel: "南あわじ市", answerScope: "area", regionId: "awaji", evidenceType: "産地", sourceIds: ["D42"] },
      { id: "HMG-069", specialty: "淡路島サクラマス", prompt: "淡路島サクラマスの産地はどこですか？", answerId: "28224", answerLabel: "南あわじ市", answerScope: "area", regionId: "awaji", evidenceType: "特産", sourceIds: ["D44"] },
      { id: "HMG-070", specialty: "真珠核", prompt: "真珠核の主産地はどこですか？", answerId: "28205", answerLabel: "洲本市", answerScope: "area", regionId: "awaji", evidenceType: "主産地", sourceIds: ["A"] },
      { id: "HMG-071", specialty: "しらさぎ染", prompt: "しらさぎ染の産地はどこですか？", answerId: "28201", answerLabel: "姫路市", answerScope: "area", regionId: "naka", evidenceType: "産地", sourceIds: ["B"] }
      ,{ id: "HMG-072", specialty: "灘五郷の日本酒", prompt: "灘五郷の日本酒の産地はどこですか？", answerId: "28102", answerIds: ["28102","28101","28204"], answerLabel: "神戸市灘区・東灘区・西宮市", answerScope: "area", regionId: "kobe", evidenceType: "複数の主産地", sourceIds: ["D46"] }
    ]
  };

  const READINGS = {
    "有馬籠":"ありまかご","名塩紙":"なじおがみ","三田青磁":"さんだせいじ","三田鈴鹿竹器":"さんだすずかたけき",
    "宝殿石（竜山石）":"ほうでんせき（たつやまいし）","山田錦":"やまだにしき","播州織":"ばんしゅうおり","播州釣針":"ばんしゅうつりばり",
    "杉原紙":"すぎはらがみ","播州鎌":"ばんしゅうがま","姫革細工":"ひめかわざいく","明珍火箸":"みょうちんひばし",
    "龍野醤油":"たつのしょうゆ","赤穂緞通":"あこうだんつう","赤穂雲火焼":"あこううんかやき","播州山崎藍染織":"ばんしゅうやまさきあいぞめおり",
    "豊岡鞄":"とよおかかばん","豊岡杞柳細工":"とよおかきりゅうざいく","出石焼":"いずしやき","城崎麦わら細工":"きのさきむぎわらざいく",
    "津居山かに":"ついやまがに","朝倉山椒":"あさくらさんしょう","八鹿豚":"ようかぶた","岩津ねぎ":"いわつねぎ",
    "香住ガニ":"かすみがに","丹波布":"たんばふ","丹波大納言小豆":"たんばだいなごんあずき","丹波黒大豆":"たんばくろだいず",
    "丹波立杭焼":"たんばたちくいやき","淡路瓦":"あわじがわら","真珠核":"しんじゅかく","灘五郷の日本酒":"なだごごうのにほんしゅ"
  };
  Object.assign(READINGS, {
    "有馬の人形筆":"ありまのにんぎょうふで","神戸ワイン":"こうべワイン","神戸家具":"こうべかぐ","神戸アパレル":"こうべアパレル","真珠加工":"しんじゅかこう",
    "伊丹酒":"いたみしゅ","川西いちじく":"かわにしいちじく","明石だこ":"あかしだこ","明石焼き":"あかしやき","宝殿石（竜山石）":"ほうでんせき（たつやまいし）",
    "小野金物（家庭刃物）":"おのかなもの（かていはもの）","三木金物":"みきかなもの","ゴルフ用具":"ゴルフようぐ","姫路の菓子":"ひめじのかし",
    "福崎もち麦":"ふくさきもちむぎ","神河ゆず":"かみかわゆず","室津かき":"むろつかき","相生かき":"あいおいかき","赤穂の塩":"あこうのしお",
    "太子いちじく":"たいしいちじく","上郡モロヘイヤ":"かみごおりモロヘイヤ","佐用ホルモン焼きうどん":"さようホルモンやきうどん","宍粟自然薯":"しそうじねんじょ",
    "城崎麦わら細工":"きのさきむぎわらざいく","淡路島たまねぎ":"あわじしまたまねぎ","淡路島の線香":"あわじしまのせんこう",
    "淡路島手延べそうめん":"あわじしまてのべそうめん","淡路島3年とらふぐ":"あわじしまさんねんとらふぐ","淡路島サクラマス":"あわじしまサクラマス",
    "丹波栗":"たんばぐり","丹波篠山黒枝豆":"たんばささやまくろえだまめ","丹波篠山山の芋":"たんばささやまやまのいも","しらさぎ染":"しらさぎぞめ",
    "龍野醤油":"たつのしょうゆ","豊岡鞄":"とよおかかばん","出石焼":"いずしやき","真珠核":"しんじゅかく","揖保乃糸":"いぼのいと",
    "室津かき":"むろつかき","赤穂の塩":"あこうのしお","宍粟自然薯":"しそうじねんじょ","豊岡杞柳細工":"とよおかきりゅうざいく",
    "出石そば":"いずしそば","津居山かに":"ついやまがに","朝倉山椒":"あさくらさんしょう","八鹿豚":"ようかぶた","岩津ねぎ":"いわつねぎ",
    "香住ガニ":"かすみガニ","但馬牛":"たじまうし","丹波黒大豆":"たんばくろだいず","淡路瓦":"あわじがわら",
    "播州そろばん":"ばんしゅうそろばん","姫路おでん":"ひめじおでん","鎖":"くさり"
  });
  // 学習画面の「参考サイトを見る」で開くページ。
  // 出典一覧（sourceIds）は産地・主産地の確認根拠として別に保持する。
  const REFERENCE_LINKS = {
    "明石だこ": "https://ja.wikipedia.org/wiki/%E6%98%8E%E7%9F%B3%E3%83%80%E3%82%B3",
    "明石焼き": "https://www.maff.go.jp/j/keikaku/syokubunka/k_ryouri/search_menu/menu/40_2_hyogo.html",
    "かつめし": "https://www.maff.go.jp/j/keikaku/syokubunka/k_ryouri/search_menu/menu/40_4_hyogo.html",
    "杉原紙": "https://web.pref.hyogo.lg.jp/sr09/ie07_000000029.html",
    "播州そろばん": "https://web.pref.hyogo.lg.jp/sr09/jibasan/21.html",
    "播州鎌": "https://web.pref.hyogo.lg.jp/sr09/ie07_000000046.html",
    "神河ゆず": "https://note.com/shirasagiknit_tm/n/n8c7d7393b589",
    "室津かき": "https://www.segoshikaisan.com/history",
    "上郡モロヘイヤ": "https://mololab.com/special/oomae.html",
    "豊岡鞄": "https://web.pref.hyogo.lg.jp/sr09/jibasan/24.html",
    "豊岡杞柳細工": "https://genbudo-museum.jp/kiryu/",
    "出石焼": "https://web.pref.hyogo.lg.jp/sr09/jibasan/28.html",
    "城崎麦わら細工": "https://web.pref.hyogo.lg.jp/sr09/ie07_000000033.html",
    "出石そば": "https://toyooka-tourism.com/recommend/food/izushi_soba/",
    "津居山かに": "https://toyooka-tourism.com/recommend/food/tsuiyama_kani/",
    "香住ガニ": "https://www.kami-tourism.com/feature/kani#",
    "但馬牛": "https://ja.wikipedia.org/wiki/%E4%BD%86%E9%A6%AC%E7%89%9B",
    "丹波大納言小豆": "https://www.ja-tanbasasayama.or.jp/brand/%E4%B8%B9%E6%B3%A2%E7%AF%A0%E5%B1%B1%E5%A4%A7%E7%B4%8D%E8%A8%80%E5%B0%8F%E8%B1%86",
    "丹波栗": "https://tamba-yanagawa.co.jp/%E4%B8%B9%E6%B3%A2%E3%81%AE%E7%89%B9%E7%94%A3%E5%93%81/%E4%B8%B9%E6%B3%A2%E6%A0%97",
    "丹波篠山黒枝豆": "https://www.ja-tanbasasayama.or.jp/brand/kuroedamame",
    "淡路瓦": "https://ja.wikipedia.org/wiki/%E6%B7%A1%E8%B7%AF%E7%93%A6",
    "淡路島3年とらふぐ": "https://www.awajishima-kanko.jp/awaji/torafugu/",
    "灘五郷の日本酒": "https://ja.wikipedia.org/wiki/%E7%81%98%E4%BA%94%E9%83%B7"
  };
  HYOGO_MEISAN_DATA.questions.forEach(question => {
    question.reading = READINGS[question.specialty] || "";
    question.displaySpecialty = question.reading ? question.specialty + "（" + question.reading + "）" : question.specialty;
    question.infoUrl = REFERENCE_LINKS[question.specialty] || "";
  });
  window.HYOGO_MEISAN_DATA = HYOGO_MEISAN_DATA;
})();
